version: '3.9'

networks:
  postgres-network:
    external: true

volumes:
  postgresdb:
    external: true

services:
  teste-postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data
    networks :
      - postgres-network
    environment:
      - POSTGRES_PASSWORD=Postgres2018!
  teste-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15432:80
    networks :
      - postgres-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=yurialcantara03@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=PgAdmin2018!
    depends_on:
    - teste-postgres
  spring:
    image: yurialcantara03/gymcontrol:SNAPSHOT-1.0
    ports:
      - 8080:8080
    depends_on:
    - teste-postgres
