version: '3.9'

networks:
  postgres-network:
    external: true

volumes:
  postgresdb:
    external: true

services:
  spring:
    image: yurialcantara03/gymcontrol:SNAPSHOT-1.0
    ports:
      - 8080:8080
    depends_on:
      - postgres
