spring:
  profiles:
    active:
  datasource:
    url: '${JDBC_DATABASE_URL}'
    driverClassName: 'org.postgresql.Driver'
    password: '${JDBC_DATABASE_PASSWORD}'
    username: '${JDBC_DATABASE_USERNAME}'
    validationQuery: 'SELECT 1'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: 'org.hibernate.cfg.ImprovedNamingStrategy'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
# jwt
origens:
  jwt:
    secret: '${SECRET_JWT}'
    expiration: '${EXPIRATION_TIME}'
  jackson:
    serialization:
      fail-on-empty-beans: false